setup.py

The dependency was introduced in 1f87ae2cef824d2347885dc64b11ddbdc95082eb but not explicitly declared.

Make dependency on requests explicit

---

CHANGELOG.md
data_integration/commands/sql.py
setup.py

`ON CONFLICT DO UPDATE` syntax requires mentioning the unique key that is present in the target table, for it to work.
This makes upserting, using this method, into partitioned tables impossible in Postgresql 10, and only possible in Postgresql 11 if it's partitioned on a scalar value (not expression).
This makes it difficult to upsert into a table partitioned by a chunk, with the chunking function present only in the DWH.
For example:
```
CREATE TABLE foo (
id1,
id2
) PARTITION BY (compute_chunk(id2));
CREATE TABLE foo_1 PARTITION OF foo FOR VALUES IN (1);
```
Will not support this style of partitioning, in Postgresql 11.
This is solved by this commit, that adds the option to do, instead of this:
```
INSERT INTO foo
SELECT * FROM foo_upsert
ON CONFLICT (id1) DO UPDATE SET …
```

Add explicit upsert (update + insert commands)

---

CHANGELOG.md
data_integration/config.py
data_integration/logging/logger.py
data_integration/ui/node_page.py

We don't want passwords saved to any disk/DB or shown in any UI so we need the ability to mask them. This masks passwords in the log (before it's actually shown/written) and in the node pages. I'm not sure if there are more places.

Add Ability to mask passwords in the UI and in saved Events

---

CHANGELOG.md
data_integration/incremental_processing/file_dependencies.py
data_integration/incremental_processing/processed_files.py
data_integration/logging/run_log.py
data_integration/ui/run_time_chart.sql

This changes the timestamps in all mara tables in data-integration to include timezones. This enables us to properly use these timestamps in monitoring.

Timezones everywhere

---

data_integration/execution.py
data_integration/logging/events.py
data_integration/logging/run_log.py

When closing a browser window (or press reload during a running ETL), the generator gets closed with GeneratorExit but we didn't close the runs/node_runs.
Similar things happened when the process was killed by SIGINT.
Now we close the runs/node_runs on both an aborted window/reload and SIGINT.

Fix open runs after browser reload

---

data_integration/commands/sql.py

When having a partitioned table where incremental load is inserted into, this speeds up the insert by making scanning the dst table parallel
Comparing the following queries (all resulting in zero results as the insert already happened):
```SQL
-- Uses Append on a Seq Scan on all children with a Hash Right Join
Explain Analyse
SELECT src.*
FROM os_data.whatever_upsert src
LEFT JOIN os_data.whatever dst
ON dst."id" = src."id"
WHERE dst.* IS NULL
-- Execution Time: 58464.012 ms
```
```SQL
-- Uses Parallel Append on a Parallel Seq Scan with a Parallel Hash Anti Join
Explain Analyse
SELECT src.*
FROM os_data.whatever_upsert src
LEFT JOIN os_data.whatever dst
ON dst."id" = src."id"
WHERE dst.id IS NULL
-- Execution Time: 14804.001 ms
```
```SQL
-- Again Uses Parallel Append on a Parallel Seq …
```

Speedup incremental insert into partitioned tables

---

CHANGELOG.md
data_integration/execution.py

On my mac on py3.7 I get RuntimeError('context has already been set')
when multiprocessing.set_start_method('fork') is run during the the second
pipeline run (the first is fine).
```python
Debugging middleware caught exception in streamed response at a point where response headers were already sent.
Traceback (most recent call last):
File ".venv/lib/python3.7/site-packages/werkzeug/wsgi.py", line 507, in __next__
return self._next()
File ".venv/lib/python3.7/site-packages/werkzeug/wrappers/base_response.py", line 45, in _iter_encoded
for item in iterable:
File "packages/data-integration/data_integration/ui/run_page.py", line 108, in process_events
for event in execution.run_pipeline(pipeline, nodes, with_upstreams):
File "packages/data-integration/data_integration/execution.py", line 45, …
```

Fix for RuntimeError on second local pipeline run on py3.7

---

data_integration/commands/sql.py
data_integration/incremental_processing/file_dependencies.py
data_integration/incremental_processing/incremental_copy_status.py

There are two places where we could end up with inconsistent state between what the DB has and what the incremental copy state/ the file dependency hashes know about:
* Incremental copy: If one would do a TRUNCATE/rebuild of the target table and the resulting full load would error, the next run would be an incremental one (as the old comparison value would still be there) despite the table not fully loaded
* file dependencies: if you do a deploy, which results in a rerun and this rerun fails + this deploy is then reverted, the old file dependencies would match and not trigger a rerun despite the DB not being in a fully functional state  
In both cases, we now simply delete the old state before the action (copy/execute) is attempted. This should trigger a full copy in the next run in case …

Fix inconsistent state after error

---

data_integration/ui/cli.py

In certain cases these show up as plain escape sequences and this gets rid if it.
Also fixes a bug in the help output of data-integration.ui.run: you cannot specify multiple pipelines, if you want that, you have to specify the parent as pipeline and the specific pipelines as nodes.

Make it possible to disable output coloring in command line etl runs

---

CHANGELOG.md
data_integration/execution.py
setup.py

The problem was that a) the frontend generated timestamps without timezones which postgresql then interpreted as the UTC but which were actually in the timezone which you ran the python code and b) the closing of open runs after an exception which kills the ETL runner itself (not individual tasks) after an error happened to insert a timestamp with timezone of the time on the postgresql server.
-> the error only happens when an exception happens which triggers this code path, e.g. because something shuts down the the runner (e.g. docker instance is shut down or ctrl+c on the command line).
Should fix https://github.com/mara/mara-example-project/issues/12

Fix Problems when frontend and database are in a different timezone

---

data_integration/logging/node_cost.py

We don't want to include broken executions in the node cost calculation. Not succeeded node executions normally don't have an realistic execution time.

ignore not succeeded executions in cost calculation

---

data_integration/events.py
data_integration/execution.py
data_integration/logging/pipeline_events.py
data_integration/notification/notifier.py
data_integration/ui/cli.py
data_integration/ui/static/run-page.js

Two problems in this PR: 
* No slack message when the mara DB is unreachable ("Notify when the runlogger.handle_event() throws an exception" // "Make event handling robust against exceptions during handling" and "Make the commandline only succeed if a RunFinished event arrived" make it more robust in general)
* Old error messages in slack when used in the browser and using multiple runs with errors without restarting flask ("Clean the message cache when a pipeline run starts and finishes")
The first showed up when the mara DB was shut down unexpectedly and we didn't get a slack notification (until our alerting based on last finish times kicked in). the second when you do SQL only fixes which need no restart...

Event logging in case of error

---

data_integration/config.py
data_integration/execution.py
data_integration/pipelines.py

allows to configure a default value for the max_retries prameter of a task globally via config default_task_max_retries()

add config default_task_max_retries

---

data_integration/execution.py
data_integration/logging/run_log.py

This makes some attempts to clean up during shutdown.
* The main thing is the atexit function in the `run_pipeline` function which simply closes a run/node_run when shutting down.
* The atexit in `run()` will shutdown any still running processes.
* It also attempts to kill the run_process when the run_pipeline process is shut down via strg+c. This should trigger the atexit function in `run()` so at least the children are killed. This does not do any attempt to do the same for any other signal yet
Also included is a fix to actually check all ancestors of a task when checking if any of them is already failed -> the effect is that we do not schedule any tasks from an already queued sub pipelines (like a parallel task) in case the parent of that subpipeline is failed.
With this in place I …

Cleaner shutdown

---

mara_pipelines/logging/logger.py

During the renaming the config item was changed as directly imported and therefore not anymore patchable. Change it back to importing the module and using it from there.

Fix missing password masks in log

---

mara_pipelines/commands/sql.py

There is a small typo in mara_pipelines/commands/sql.py.
Should read `comparison` rather than `comparision`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

docs: fix simple typo, comparision -> comparison

---

mara_pipelines/commands/sql.py
mara_pipelines/parallel_tasks/sql.py
setup.py

Since mara_db version 4.7.1 the echo_queries parameter is by default taken from `mara_db.config.default_echo_queries` when it is `None`.
The config is by default set to True, so, we can safely remove all `echo_queries=True` calls in mara_pipeline.
With this PR the mara_db.config.default_echo_queries config will apply to mara_pipeline as well.

use echo_queries from mara_db.config.default_echo_queries

---

mara_pipelines/shell.py

Currently stderr is only read after stdout ended sending (= after the called bash command ended). With this change, stderr and stdout is read simultanously via two separate threads to make it possible that stderr is read before the command ended.
Create file `test-stderr.sh`:
``` bash
#/bin/bash
for number in {1..15}
do
>&2 echo "$number ..."
sleep 1
done
exit 0
```
Create file `test-stdout.sh`:
``` bash
#/bin/bash
for number in {1..15}
do
echo "$number ..."
sleep 1
done
exit 0
```
When you set up a pipeline with a `RunBash` command calling `test-stdout.sh`, you will see the output during execution. When you do the same with calling `test-stderr.sh`, you will get the log output in mara only after the shell script ended.
With this pull request, this behavior will change so that …

fix read stderr during command execution

---

mara_pipelines/commands/sql.py

Main thing is the last commit which handled the case that the last modification comparison query does not return any value but still succeeds (=would load no data). In that case we now succeed the copy task but don't actually attempt to load data.
This also adjusts the printed messages from Copy to be more readable (I hope) and adds imports and asserts to make my IDE happy...

Fix CopyIncrementally with no data

---

mara_pipelines/execution.py
mara_pipelines/logging/run_log.py
setup.py
tests/test_execute_pipeline.py

Adds a simple unit test for a pipeline execution. To do so I changed the code that the 'mara' db is optional during the pipeline execution:
* node cost is not taken from the database
* `RunLogger` will skip logging events to the database when 'mara' database is not defined

add a simple pipeline unit test without mara db

---

mara_pipelines/execution.py
tests/test_execute_pipeline.py

The internal exitcode handling of a process changed since python 3.8 (https://github.com/python/cpython/issues/84275) which caused that when executing a pipeline through the UI the exit code from the process is 1 even when using `sys.exit(0)`. When we use the same multiprocessing context this seems to be handled properly in python and we get the correct exit code.

fix exitcode of process issue since python 3.8

---

mara_pipelines/commands/http.py
mara_pipelines/shell.py

add HttpRequest command #78

---

mara_pipelines/logging/pipeline_events.py

On docker the `flask mara_pipelines.ui.run-interactively` fails with
This is a fix for this: According to the python documentation [os.getlogin()](https://docs.python.org/3/library/os.html#os.getlogin), `getpass.getuser()` should be used.

fix get_user_display_name on docker

---

mara_pipelines/pipelines.py

Hides the empty tasks in the internal pipeline behind `ParallelTask` when `commands_before` and `commands_after` of the parallel task is empty.

hide empty before/after task in ParallelTask

---

mara_pipelines/commands/sql.py
mara_pipelines/incremental_processing/file_dependencies.py
mara_pipelines/incremental_processing/incremental_copy_status.py
mara_pipelines/incremental_processing/processed_files.py
mara_pipelines/incremental_processing/reset.py
mara_pipelines/logging/node_cost.py
mara_pipelines/logging/run_log.py
mara_pipelines/parallel_tasks/files.py
mara_pipelines/ui/last_runs.py
mara_pipelines/ui/run_time_chart.py
setup.cfg

Use generic cursor context for future support of other database engines for the `mara` db.
Requires mara_db 4.9+

use generic cursor context

---

mara_pipelines/commands/bash.py
mara_pipelines/commands/files.py
mara_pipelines/commands/http.py
mara_pipelines/commands/python.py
mara_pipelines/commands/sql.py
mara_pipelines/config.py
mara_pipelines/execution.py
mara_pipelines/incremental_processing/file_dependencies.py
mara_pipelines/incremental_processing/incremental_copy_status.py
mara_pipelines/incremental_processing/processed_files.py
mara_pipelines/incremental_processing/reset.py
mara_pipelines/logging/logger.py
mara_pipelines/logging/node_cost.py
mara_pipelines/logging/run_log.py
mara_pipelines/notification/notifier.py
mara_pipelines/notification/slack.py
mara_pipelines/notification/teams.py
mara_pipelines/parallel_tasks/files.py
mara_pipelines/parallel_tasks/python.py
mara_pipelines/parallel_tasks/sql.py
mara_pipelines/pipelines.py
mara_pipelines/shell.py
mara_pipelines/ui/cli.py
mara_pipelines/ui/dependency_graph.py
mara_pipelines/ui/last_runs.py

Add typing for parameters + fix several small issues in code

add typing + fix small issues

---

mara_pipelines/incremental_processing/file_dependencies.py
mara_pipelines/incremental_processing/incremental_copy_status.py
mara_pipelines/incremental_processing/processed_files.py
mara_pipelines/logging/run_log.py
setup.cfg

fixes the following SQLAlchemy warning:

fix SQLAlchemy warning about declarative_base moved in 2.0

---

.github/workflows/build.yaml
Makefile
docs/commands.rst
mara_pipelines/commands/files.py
pyproject.toml
setup.cfg
tests/README.md
tests/db_test_helper.py
tests/docker-compose.yml
tests/local_config.py
tests/mssql/names.csv
tests/mssql/names_dll_create.sql
tests/mssql/names_dll_drop.sql
tests/mssql/test_command_ReadFile.py
tests/mssql/test_mssql.py
tests/postgres/test_command_ReadFile.py
tests/postgres/test_postgres.py
tests/postgres/test_postgres_ddl.sql

Add a command to write a sql query result to a file in a specific format.
- requires https://github.com/mara/mara-db/pull/64 (not merged yet)
- mentioned in #80, but does not require package `mara_storage`

add WriteFile command

---

README.md
docs/example.md
mara_pipelines/__init__.py
mara_pipelines/cli.py
mara_pipelines/ui/cli.py
tests/mssql/test_mssql.py
tests/postgres/test_postgres.py
tests/test_execute_pipeline.py

This adds the `mara-pipelines` click command group and deprecates the call of click commands:
1. Commands can be executed via `flask mara-pipelines run`
2. The old commands e.g. `flask mara_pipelines.ui.run ...` will throw a warning but still work
3. the cli commands are moved from `mara_pipelines.ui.cli` to `mara_pipelines.cli` to use the same implementation across all mara modules.
**Note:**
* with [mara-app#48](https://github.com/mara/mara-app/pull/48) it is possible to shorten the click command name to support cli calls like `mara pipelines run --path ...`

add mara-pipelines click command group
